plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
    maven { name = 'Nucleoid'; url = 'https://maven.nucleoid.xyz/' }

    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                    url = "https://api.modrinth.com/maven"
            }
        }
        // forRepositories(fg.repository) // Uncomment when using ForgeGradle
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	implementation "eu.pb4:polymer-core:${project.polymer_version}"
	implementation "eu.pb4:polymer-common:${project.polymer_version}"
	implementation "eu.pb4:polymer-resource-pack:${project.polymer_version}"
	implementation "eu.pb4:polymer-autohost:${project.polymer_version}"

	include "eu.pb4:polymer-core:${project.polymer_version}"
	include "eu.pb4:polymer-common:${project.polymer_version}"
	include "eu.pb4:polymer-resource-pack:${project.polymer_version}"
	include "eu.pb4:polymer-autohost:${project.polymer_version}"

        implementation "maven.modrinth:K01OU20C:RRJmyPMW"                    
        include "maven.modrinth:K01OU20C:RRJmyPMW"
}

processResources {
	def version = project.version
	inputs.property "version", version
	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

tasks.named('processResources', ProcessResources) {
    filePermissions {
        unix("644")
    }
    dirPermissions {
        unix("755")
    }
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}
